### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by YuiZhushi** [lobehub/sd-webui-lobe-theme#464]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 📦 SD Wbui 版本或提交 | Version or Commit

1.6.0-2

### 🐛 问题描述 | Bug Description

暂无内容。请添加模型到以下目录：
F:\Aaaki diffusion\sd-webui-aki-v4.4\embeddings
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/125752787/6597725d-1e1c-4f45-bcd7-2f23aba3b3bf)

It aready have some embdding in folder but doesn`t show in Embddings Tab
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/125752787/fdb6cb36-9056-42b6-bccf-dd69981e20d5)

Lora and Model and Hypernetwork Tab are ok
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/125752787/54cae903-2153-42af-af24-8e1c65ac5f82)
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/125752787/125c55a7-326a-4d8c-b3ca-8d24c095535b)
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/125752787/160f6147-0a08-47d4-b6e5-4a7231f9ddb2)

### 🚦 期望结果 | Expected Behavior

embdding show in Embddings Tab

### 📷 复现步骤 | Recurrence Steps

i don`t know how to recurrence steps
bug happen after update extension

### 📝 补充信息 | Additional Information

aready clean web cookie but no use

**Comment by kaalibro** [comment]
Can't reproduce. Try disabling the theme extension and see if the problem remains. If so, perhabs the reason is something else. Share the terminal output after WebUI launch.

![Screenshot 2023-11-23 024631](https://github.com/lobehub/sd-webui-lobe-theme/assets/44464226/8894ed14-321d-42dc-beef-ec2d9babbf44)

SD WebUI v1.6.0-356 fc83af44
Lobe Theme v3.0.11 4fe87e38
Edge v119.0.2151.72
Windows 11

**Comment by YuiZhushi** [comment]
after i disabling and reactivate extension the bug fixed.
Thank you for your help
